### ISSUE TITLE
Cannot resolve module 'services/version-service'

### ISSUE THREAD

**Issue by svassr** [d3spis3d/generator-angular-es6-webpack#1]
At fresh start, when running `gulp serve`, I got this error `Cannot resolve module 'services/version-service'` `@ ./app/app.js 19:0-35`. 

Running `gulp karma` error says `Cannot find module "services/version-service"` `test/spec/tests.webpack.js:13093 <- webpack:///app/app.js:9:0`

Indeed `version-service` is not defined and imported in app.js at line 9.  I had to remove it there and at line 10 as well.

**Comment by d3spis3d** [comment]
The `version-service` is created during the `gulp build` task. One a fresh start you will need to run this task before serving or running tests.

**Comment by amostech** [comment]
This was useful to me. I am using this generator. 

Probably best if you put this info in the README.md file. I was about to create an issue haha.

Thanks.

**Comment by d3spis3d** [comment]
Thanks, I have updated the README to add this info. Closing the issue, reopen if there are still any issues surrounding this.
